using System.Text.Json.Serialization;

namespace OresToFieldGuide
{
	/// <summary>
	/// A .NET represnetation of a Patchouli Entry
	/// <para></para>
	/// <a href="https://vazkiimods.github.io/Patchouli/docs/reference/entry-json">Patchouli Docs</a>
	/// </summary>
	[Serializable]
	public class PatchouliEntry
	{
		[JsonPropertyName("__credits__")]
		public string Credits => "This page was automatically generated by OresToFieldGuide.";

		[JsonPropertyName("name")]
		public required string Name { get; set; }

		[JsonPropertyName("icon")]
		public required string Icon { get; set; }

		[JsonPropertyName("category")]
		public string Category { get; } = "tfc:tfg_ores";

		[JsonPropertyName("read_by_default")]
		public bool ReadByDefault { get; set; } = true;

		[JsonPropertyName("priority")]
		public int? Priority { get; set; }

		[JsonPropertyName("advancement")]
		public string? RequiredAdvancement { get; set; }

		[JsonPropertyName("secret")]
		public bool IsSecret { get; set; } = false;

		[JsonPropertyName("pages")]
		public required List<PatchouliPage> Pages { get; set; }

		[JsonPropertyName("sortnum")]
		public int? SortNum { get; set; }


		[JsonIgnore]
		public string? FileNameWithoutExtension { get; set; }
	}
}