package io.github.tfgcn.langsync.service.model;

import lombok.Data;

import java.util.List;

@Data
public class FileScanRequest {
    private String workspace;// Where you put your Tools-Modern. e.g `D:\workspace`
    private String sourceFilePattern;// e.g. test/**/%src_lang%/**.json
    private String translationFilePattern;// Mapping pattern. e.g. test/%lang%/%original_path%/%original_file_name%
    private String srcLang;// source language. e.g. en_us. %src_lang%
    private String destLang;// destination language. e.g. zh_us. %lang%
    private List<String> ignores;// the file you want to ignore/ e.g. The `ore_veins.jon` which was generated by another application.
}
